[INIT] 프로젝트 관련 엔티티 생성
Builzer/builzer-backend pull request #10
Opened 2024-06-26 11:19 UTC by CokeLee777

2024-06-26 11:36 UTC, MJun111 approved these changes

2024-06-26 11:36 UTC, MJun111 commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/SupportedLanguageJpaEntity.kt
> +        @Column(name = "language_provider", nullable = false, updatable = false)
enum

2024-06-26 12:55 UTC, CokeLee777 commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/SupportedLanguageJpaEntity.kt
> +        @Column(name = "language_provider", nullable = false, updatable = false)
낼 바꿔놓을게요

2024-06-26 13:57 UTC, CokeLee777 commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/SupportedLanguageJpaEntity.kt
> +        @Column(name = "language_provider", nullable = false, updatable = false)
코드리뷰 반영했습니다~!

2024-06-27 12:51 UTC, wakkpu requested changes

2024-06-27 12:51 UTC, wakkpu commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/BuildHistoryJpaEntity.kt
> +        val buildTime: Int,
이런거 _at으로 쓴다고 했던거 같은데 일단 erd대로?

2024-06-27 12:51 UTC, wakkpu commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/ProjectMemberJpaEntity.kt
> +        @Column(name = "plan_name", nullable = false, updatable = false)
필드명 수정해주세요

2024-06-27 12:55 UTC, CokeLee777 commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/BuildHistoryJpaEntity.kt
> +        val buildTime: Int,
이 컬럼은 date가 아닌 걸린 시간이에요..

2024-06-27 12:55 UTC, CokeLee777 commented on src/main/kotlin/com/builzer/backend/project/adapter/out/persistence/entity/ProjectMemberJpaEntity.kt
> +        @Column(name = "plan_name", nullable = false, updatable = false)
수정했습니다. 확인 부탁드립니다.

2024-06-28 14:56 UTC, wakkpu approved these changes

2024-06-28 15:41 UTC, merged